#include<stdio.h>
#include<conio.h>
#include<math.h>
void main(void)
{ int x[20],i,n,s=0,p=1;
 clrscr();
printf("Culegeti marimea masivului");
scanf("%d",&n);
printf("Culegeti masivul\n");
scanf("x[%d]=",i);
scanf ("%d",&x[i]);
for(i=0;i<n;i++)
printf("%d,&x[i]);
if(x[i]>n)s+=x[i];
if(x[i]>n)p*=x[i];
printf("\n Suma elementelor pozitive =%d",s);
printf("\n Produsul elementelor pozitive=%d",p);
getch();
}

