#include<stdio.h>
#include<conio.h>
#include<math.h>
#include <stdlib.h>

void main(void){
{
  int x,a,b,c,l,p;
  float w,k;

  printf ("\nculege volorile pentru ,x,a,b\n");
  scanf  ("%d%d%d%d%d%d",&x,&a,&b);
  w=pow(cos( pow(x,3),2)-x/sqrt(pow(a,2)+pow(b,2))+b*pow(tan(x),2)*x-a/pow(sin(x/a),2);

  printf("\n culege o cifra \n");
  scanf(%d",&c);
  k=(6+c)/f;
  p=float(k);
  printf("\nf=%f citul este =%f si partea intreaga=% d",f,k,p);
  if (fmod(p,2)=0)
  printf("\n partea intreaga este para\n');
  else printf("\n partea intreaga este impara\n");
  getch();
}
